<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresoMantenimiento.aspx.cs" Inherits="Obligatorio_1_prog2.IngresoMantenimiento" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        Fecha de mantenimeinto :&nbsp;
        <asp:TextBox ID="TxtFecha" class="form-control" runat="server" TextMode="Date"></asp:TextBox>
    </p>
    <p>
        Descripción : <asp:TextBox ID="TxtDescripcion" class="form-control"  runat="server"></asp:TextBox>
    </p>
    <p>
        Barco :
        <asp:DropDownList ID="DD_Barco" class="form-select" runat="server" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        Tipo de mantenimiento :
        <asp:DropDownList ID="DD_TipoM" class="form-select" runat="server" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        Encargado responsable :
        <asp:DropDownList ID="DD_Encargado" class="form-select" runat="server" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Button ID="BtnGuardar" class="btn-primary" runat="server" Text="Guardar" OnClick="BtnGuardar_Click" />
    </p>
    <p>
        &nbsp;</p>
    <div class="orden">
        <asp:GridView ID="GridMantenimientos" class="table table-striped table-hover" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridMantenimientos_RowDeleting">
        </asp:GridView>
    </div>
</asp:Content>
