<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresoTipoMantenimiento.aspx.cs" Inherits="Obligatorio_1_prog2.IngresoTipoMantenimiento" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
    Codigo :
    <asp:TextBox ID="TxtCodigo" class="form-control" runat="server"></asp:TextBox>
</p>
<p>
    Precio base :
    <asp:TextBox ID="TxtPrecioBase" class="form-control" runat="server"></asp:TextBox>
</p>
<p>
    Descripción :
    <asp:TextBox ID="TxtDescripcion" class="form-control" runat="server"></asp:TextBox>
</p>
<p>
    <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
</p>
<p>
    <asp:Button ID="BtnGuardar" class="btn-primary" runat="server" OnClick="BtnGuardar_Click" Text="Guardar" />
</p>
<p>
    &nbsp;</p>
<p>
    <asp:GridView ID="GridTiposMantenimiento" class="table table-striped" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridTiposMantenimiento_RowDeleting">
    </asp:GridView>
</p>
</asp:Content>
