<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresoMantenimiento.aspx.cs" Inherits="Obligatorio_1_prog2.IngresoMantenimiento" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        Fecha de mantenimeinto :&nbsp;
        <asp:TextBox ID="TxtFecha" runat="server" TextMode="Date"></asp:TextBox>
    </p>
    <p>
        Descripción : <asp:TextBox ID="TxtDescripcion" runat="server"></asp:TextBox>
    </p>
    <p>
        Barco :
        <asp:DropDownList ID="DD_Barco" runat="server" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        Tipo de mantenimiento :
        <asp:DropDownList ID="DD_TipoM" runat="server" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        Encargado responsable :
        <asp:DropDownList ID="DD_Encargado" runat="server" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Button ID="BtnGuardar" runat="server" Text="Guardar" OnClick="BtnGuardar_Click" />
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:GridView ID="GridMantenimientos" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridMantenimientos_RowDeleting">
        </asp:GridView>
    </p>
</asp:Content>
