<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresoEncargados.aspx.cs" Inherits="Obligatorio_1_prog2.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        &nbsp;</p>
<p>
        &nbsp;</p>
        Cedula :
        <asp:TextBox ID="TxtCedula" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Nombre :
        <asp:TextBox ID="TxtNombre" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Correo :
        <asp:TextBox ID="TxtCorreo" class="form-control" runat="server" TextMode="Email"></asp:TextBox>
    </p>
    <p>
        Cantidad de personas a cargo : <asp:TextBox ID="TxtCantPersonas" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Button ID="BtnIngresar" runat="server" class="btn-primary" OnClick="BtnIngresar_Click" Text="Ingresar" />
        <asp:Button ID="BtnBuscar" runat="server" Text="Buscar" class="btn-success" OnClick="BtnBuscar_Click" />
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:GridView ID="GridEncargados" class="table table-hover" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridEncargados_RowDeleting">
        </asp:GridView>
    </p>
</asp:Content>
