<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresoUsuario.aspx.cs" Inherits="Obligatorio_1_prog2.IngresoUsuario" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        <br />
    </p>
    <p>
        &nbsp;</p>
    <p>
        Nombre:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:TextBox ID="txtNombre" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Cedula:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="txtCedula" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        ID Usuario:&nbsp;&nbsp;
        <asp:TextBox ID="txtID" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Contraseña:
        <asp:TextBox ID="txtContraseña" class="form-control" runat="server" TextMode="Password"></asp:TextBox>
    </p>
    <p>
        Correo:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="txtCorreo" class="form-control" runat="server" TextMode="Email"></asp:TextBox>
    </p>
    <p>
        &nbsp;</p>
        <h3>Permisos:</h3>
    <p>
        Asignar Tripulación:<asp:CheckBox ID="CheckBox1" runat="server" />
    <p>
        Ingresar Cargos:<asp:CheckBox ID="CheckBox2" runat="server" />
<p>
        Ingresar Tripulantes:<asp:CheckBox ID="CheckBox3" runat="server" />
</p>
<p>
        Ingresar Encargados:<asp:CheckBox ID="CheckBox4" runat="server" />
</p>
<p>
        Ingresar Mantenimiento:
        <asp:CheckBox ID="CheckBox5" runat="server" />
</p>
<p>
        Ingresar Tipo de Mantenimiento:<asp:CheckBox ID="CheckBox6" runat="server" />
</p>
<p>
        Ingreso Usuario:<asp:CheckBox ID="CheckBox7" runat="server" />
</p>
<p>
        Registro Barcos:<asp:CheckBox ID="CheckBox8" runat="server" />
</p>
<p>
        Historial Mantenimientos:<asp:CheckBox ID="CheckBox9" runat="server" />
</p>
<p>
        Historial Cambios:<asp:CheckBox ID="CheckBox10" runat="server" />
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="#FF3300"></asp:Label>
    </p>
    <p>
        <asp:Button ID="btnGuardar" runat="server" class="btn-primary" OnClick="btnGuardar_Click" Text="Guardar" />
        <asp:Button ID="btnBuscar" runat="server" class="btn-success" OnClick="btnBuscar_Click" Text="Buscar" />
    </p>
    <p>
        &nbsp;</p>
    <div class="orden">
        <asp:GridView ID="GridUsuario" class="table table-striped table-dark table-hover" runat="server" AutoGenerateColumns="False" Width="200px" AutoGenerateDeleteButton="True" OnRowDeleting="GridUsuario_RowDeleting">
            <Columns>
                <asp:BoundField DataField="nombreUsuario" HeaderText="Usuario" />
            </Columns>
        </asp:GridView>
    </div>
    </asp:Content>
