<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresarCargos.aspx.cs" Inherits="Obligatorio_1_prog2.IngresarCargos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        Nombre cargo :
        <asp:TextBox ID="TxtNombreCargo" runat="server"></asp:TextBox>
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:Button ID="BtnGuardar" runat="server" Text="Guardar" OnClick="BtnGuardar_Click" />
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:GridView ID="GridCargos" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridCargos_RowDeleting">
        </asp:GridView>
    </p>
</asp:Content>
