<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresarCargos.aspx.cs" Inherits="Obligatorio_1_prog2.IngresarCargos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        Nombre cargo :
        <asp:TextBox ID="TxtNombreCargo" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Button ID="BtnGuardar" class="btn-primary" runat="server" Text="Guardar" OnClick="BtnGuardar_Click" />
    </p>
    <p>
        &nbsp;</p>
    <div class="orden">
        <asp:GridView ID="GridCargos" class="table table-hover" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridCargos_RowDeleting">
        </asp:GridView>
    </div>
</asp:Content>
