<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IngresarTripulantes.aspx.cs" Inherits="Obligatorio_1_prog2.IngresarTripulantes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        <br />
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Cedula:"></asp:Label>
&nbsp;<asp:TextBox ID="TxtCedula" runat="server" class="form-control"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label2" runat="server" Text="Nombre:"></asp:Label>
        <asp:TextBox ID="TxtNombre" runat="server" class="form-control"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label3" runat="server" Text="Correo:"></asp:Label>
&nbsp;
        <asp:TextBox ID="TxtCorreo" runat="server" TextMode="Email" class="form-control"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label4" runat="server" Text="Cargo:"></asp:Label>
&nbsp;&nbsp;&nbsp;
        <asp:DropDownList ID="DDCargo" runat="server" class="form-select" AppendDataBoundItems="True">
            <asp:ListItem>(Seleccionar)</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Button ID="btnIngresar" class="btn-primary" runat="server" OnClick="btnIngresar_Click" Text="Ingresar" />
        <asp:Button ID="btnBuscar" class="btn-success" runat="server" Text="Buscar" OnClick="btnBuscar_Click" />
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:GridView ID="GridTripulantes" class="table table-warning table-hover" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridTripulantes_RowDeleting">
        </asp:GridView>
    </p>
    <p>
        &nbsp;</p>
        <h3>Cantidad de tripulantes registrados :</h3>
        <asp:Label ID="TotalTripulantes" runat="server"></asp:Label>
        <h3>Cantidad por tipo:</h3>
     <div class="orden">
          <asp:GridView ID="GridTipoTripulante" class="table table-dark table-striped" runat="server">
          </asp:GridView>
      </div>
    <p>
        &nbsp;</p>
</asp:Content>
