<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RegistroBarco.aspx.cs" Inherits="Obligatorio_1_prog2.RegistroBarco" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link rel="stylesheet" type="text/css" href="Diseño/General.css" />
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        Nombre de barco :
        <asp:TextBox ID="TxtNombreBarco" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Cantiad de pasajeros :
        <asp:TextBox ID="TxtCantPasajeros" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Cantidad maxima deTripulantes :
        <asp:TextBox ID="TxtCantMaxTripulantes" class="form-control" runat="server"></asp:TextBox>
    </p>
    <p>
        Tipo de barco :&nbsp;
        <asp:DropDownList ID="TipoBarco" class="form-select" runat="server" OnSelectedIndexChanged="TipoBarco_SelectedIndexChanged" AutoPostBack="True">
            <asp:ListItem Selected="True">(Seleccionar)</asp:ListItem>
            <asp:ListItem Value="BarcoLento">Barco Lento</asp:ListItem>
            <asp:ListItem Value="BarcoRapido">Barco Rapido</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        <asp:Label runat="server" Text="Velocidad Maxima : " ID="LabelVelMax"  Visible="False"></asp:Label> 
        <asp:TextBox ID="TxtVelMaxima" class="form-control" runat="server" Visible="False"></asp:TextBox>
    </p>
    <p>
        <asp:Label runat="server" Text="Cantidad de vehiculos : " ID="LabelCantVehi" Visible="False"></asp:Label>
        <asp:TextBox ID="TxtCantVehiculos" class="form-control" runat="server" Visible="False"></asp:TextBox>
    </p>
    <p>
        <asp:Label runat="server" Text="Precio mantenimiento : " ID="LabelPrecioM" Visible="False"></asp:Label>
        <asp:TextBox ID="TxtPrecioMant" class="form-control" runat="server" Visible="False"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="LabelError" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Button ID="BtnGuardar" class="btn-primary" runat="server" OnClick="BtnGuardar_Click" Text="Guardar" />
        <asp:Button ID="BtnBuscar" class="btn-success" runat="server" OnClick="BtnBuscar_Click" Text="Buscar" />
    </p>
    <p>
        &nbsp;</p>
    <h3>Barcos Rapidos</h3>
    <div class="orden">
        <asp:GridView ID="GridBarcoRapido" class="table table-striped table-warning table-hover" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridBarcoRapido_RowDeleting">
        </asp:GridView>
    </div>
    <h3>Barcos Lentos</h3>
    <div class="orden">
        <asp:GridView ID="GridBarcoLento" class="table table-striped table-primary table-hover" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridBarcoLento_RowDeleting">
        </asp:GridView>
    </div>
</asp:Content>
